  
name: 'Test Build'

on:
  push:
    branches:
      - dev
    paths:
        - 'open-weather-radio/**'
        - '.github/workflows/**'
jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target /data \
          --docker-hub jptekservices \
          --branch dev \
          --target open-weather-radio
